### ISSUE TITLE
NEED CSS BASED ANIMATION IDEAS [FRONT-END] FOR MY NEW WEBSITE

### ISSUE THREAD

**Issue by GR8xlr8** [GR8xlr8/Front-End#1]
NEED A FRONT END CSS CODE FOR  ANY ANIMATION RELATED TO WINTER THEME
 TRY TO WRITE A NEET AND CLEAN CODE WITH WORKING AS PER INSTRUCTED

**Comment by arana2k** [comment]
Can i contribute as i have good knowledge of front end ?

**Comment by GR8xlr8** [comment]
Do you know only html and css or you have some idea regarding js also

**Comment by arana2k** [comment]
ya i also know js to some extent

**Comment by GR8xlr8** [comment]
okk wait let me assign you this issue

**Comment by GR8xlr8** [comment]
Thanks , really liked your work will be seeing you in future for further more development contributions!!
